package io.github.tomgarden.lib.pickcolor;

/**
 describe : ColorSelDialog 类所需要的颜色 ，本类来自 material-dialogs(有截取)

 <p>author : tom
 <p>time : 18-9-16 07:13
 <p>email : tom.work@foxmail.com
 <p>CSDN : https://blog.csdn.net/u014587769
 <p>Git : https://github.com/TomGarden
 */
public class ColorPalette {

    //region no sort colors
    /*public final int[] COLORS = new int[]{
            Color.parseColor("#F44336"),
            Color.parseColor("#E91E63"),
            Color.parseColor("#9C27B0"),
            Color.parseColor("#673AB7"),
            Color.parseColor("#3F51B5"),
            Color.parseColor("#2196F3"),
            Color.parseColor("#03A9F4"),
            Color.parseColor("#00BCD4"),
            Color.parseColor("#009688"),
            Color.parseColor("#4CAF50"),
            Color.parseColor("#8BC34A"),
            Color.parseColor("#CDDC39"),
            Color.parseColor("#FFEB3B"),
            Color.parseColor("#FFC107"),
            Color.parseColor("#FF9800"),
            Color.parseColor("#FF5722"),
            Color.parseColor("#795548"),
            Color.parseColor("#9E9E9E"),
            Color.parseColor("#607D8B")
    };

    public final int[][] COLORS_SUB = new int[][]{
            new int[]{
                    Color.parseColor("#FFEBEE"),
                    Color.parseColor("#FFCDD2"),
                    Color.parseColor("#EF9A9A"),
                    Color.parseColor("#E57373"),
                    Color.parseColor("#EF5350"),
                    Color.parseColor("#F44336"),
                    Color.parseColor("#E53935"),
                    Color.parseColor("#D32F2F"),
                    Color.parseColor("#C62828"),
                    Color.parseColor("#B71C1C")
            },
            new int[]{
                    Color.parseColor("#FCE4EC"),
                    Color.parseColor("#F8BBD0"),
                    Color.parseColor("#F48FB1"),
                    Color.parseColor("#F06292"),
                    Color.parseColor("#EC407A"),
                    Color.parseColor("#E91E63"),
                    Color.parseColor("#D81B60"),
                    Color.parseColor("#C2185B"),
                    Color.parseColor("#AD1457"),
                    Color.parseColor("#880E4F")
            },
            new int[]{
                    Color.parseColor("#F3E5F5"),
                    Color.parseColor("#E1BEE7"),
                    Color.parseColor("#CE93D8"),
                    Color.parseColor("#BA68C8"),
                    Color.parseColor("#AB47BC"),
                    Color.parseColor("#9C27B0"),
                    Color.parseColor("#8E24AA"),
                    Color.parseColor("#7B1FA2"),
                    Color.parseColor("#6A1B9A"),
                    Color.parseColor("#4A148C")
            },
            new int[]{
                    Color.parseColor("#EDE7F6"),
                    Color.parseColor("#D1C4E9"),
                    Color.parseColor("#B39DDB"),
                    Color.parseColor("#9575CD"),
                    Color.parseColor("#7E57C2"),
                    Color.parseColor("#673AB7"),
                    Color.parseColor("#5E35B1"),
                    Color.parseColor("#512DA8"),
                    Color.parseColor("#4527A0"),
                    Color.parseColor("#311B92")
            },
            new int[]{
                    Color.parseColor("#E8EAF6"),
                    Color.parseColor("#C5CAE9"),
                    Color.parseColor("#9FA8DA"),
                    Color.parseColor("#7986CB"),
                    Color.parseColor("#5C6BC0"),
                    Color.parseColor("#3F51B5"),
                    Color.parseColor("#3949AB"),
                    Color.parseColor("#303F9F"),
                    Color.parseColor("#283593"),
                    Color.parseColor("#1A237E")
            },
            new int[]{
                    Color.parseColor("#E3F2FD"),
                    Color.parseColor("#BBDEFB"),
                    Color.parseColor("#90CAF9"),
                    Color.parseColor("#64B5F6"),
                    Color.parseColor("#42A5F5"),
                    Color.parseColor("#2196F3"),
                    Color.parseColor("#1E88E5"),
                    Color.parseColor("#1976D2"),
                    Color.parseColor("#1565C0"),
                    Color.parseColor("#0D47A1")
            },
            new int[]{
                    Color.parseColor("#E1F5FE"),
                    Color.parseColor("#B3E5FC"),
                    Color.parseColor("#81D4FA"),
                    Color.parseColor("#4FC3F7"),
                    Color.parseColor("#29B6F6"),
                    Color.parseColor("#03A9F4"),
                    Color.parseColor("#039BE5"),
                    Color.parseColor("#0288D1"),
                    Color.parseColor("#0277BD"),
                    Color.parseColor("#01579B")
            },
            new int[]{
                    Color.parseColor("#E0F7FA"),
                    Color.parseColor("#B2EBF2"),
                    Color.parseColor("#80DEEA"),
                    Color.parseColor("#4DD0E1"),
                    Color.parseColor("#26C6DA"),
                    Color.parseColor("#00BCD4"),
                    Color.parseColor("#00ACC1"),
                    Color.parseColor("#0097A7"),
                    Color.parseColor("#00838F"),
                    Color.parseColor("#006064")
            },
            new int[]{
                    Color.parseColor("#E0F2F1"),
                    Color.parseColor("#B2DFDB"),
                    Color.parseColor("#80CBC4"),
                    Color.parseColor("#4DB6AC"),
                    Color.parseColor("#26A69A"),
                    Color.parseColor("#009688"),
                    Color.parseColor("#00897B"),
                    Color.parseColor("#00796B"),
                    Color.parseColor("#00695C"),
                    Color.parseColor("#004D40")
            },
            new int[]{
                    Color.parseColor("#E8F5E9"),
                    Color.parseColor("#C8E6C9"),
                    Color.parseColor("#A5D6A7"),
                    Color.parseColor("#81C784"),
                    Color.parseColor("#66BB6A"),
                    Color.parseColor("#4CAF50"),
                    Color.parseColor("#43A047"),
                    Color.parseColor("#388E3C"),
                    Color.parseColor("#2E7D32"),
                    Color.parseColor("#1B5E20")
            },
            new int[]{
                    Color.parseColor("#F1F8E9"),
                    Color.parseColor("#DCEDC8"),
                    Color.parseColor("#C5E1A5"),
                    Color.parseColor("#AED581"),
                    Color.parseColor("#9CCC65"),
                    Color.parseColor("#8BC34A"),
                    Color.parseColor("#7CB342"),
                    Color.parseColor("#689F38"),
                    Color.parseColor("#558B2F"),
                    Color.parseColor("#33691E")
            },
            new int[]{
                    Color.parseColor("#F9FBE7"),
                    Color.parseColor("#F0F4C3"),
                    Color.parseColor("#E6EE9C"),
                    Color.parseColor("#DCE775"),
                    Color.parseColor("#D4E157"),
                    Color.parseColor("#CDDC39"),
                    Color.parseColor("#C0CA33"),
                    Color.parseColor("#AFB42B"),
                    Color.parseColor("#9E9D24"),
                    Color.parseColor("#827717")
            },
            new int[]{
                    Color.parseColor("#FFFDE7"),
                    Color.parseColor("#FFF9C4"),
                    Color.parseColor("#FFF59D"),
                    Color.parseColor("#FFF176"),
                    Color.parseColor("#FFEE58"),
                    Color.parseColor("#FFEB3B"),
                    Color.parseColor("#FDD835"),
                    Color.parseColor("#FBC02D"),
                    Color.parseColor("#F9A825"),
                    Color.parseColor("#F57F17")
            },
            new int[]{
                    Color.parseColor("#FFF8E1"),
                    Color.parseColor("#FFECB3"),
                    Color.parseColor("#FFE082"),
                    Color.parseColor("#FFD54F"),
                    Color.parseColor("#FFCA28"),
                    Color.parseColor("#FFC107"),
                    Color.parseColor("#FFB300"),
                    Color.parseColor("#FFA000"),
                    Color.parseColor("#FF8F00"),
                    Color.parseColor("#FF6F00")
            },
            new int[]{
                    Color.parseColor("#FFF3E0"),
                    Color.parseColor("#FFE0B2"),
                    Color.parseColor("#FFCC80"),
                    Color.parseColor("#FFB74D"),
                    Color.parseColor("#FFA726"),
                    Color.parseColor("#FF9800"),
                    Color.parseColor("#FB8C00"),
                    Color.parseColor("#F57C00"),
                    Color.parseColor("#EF6C00"),
                    Color.parseColor("#E65100")
            },
            new int[]{
                    Color.parseColor("#FBE9E7"),
                    Color.parseColor("#FFCCBC"),
                    Color.parseColor("#FFAB91"),
                    Color.parseColor("#FF8A65"),
                    Color.parseColor("#FF7043"),
                    Color.parseColor("#FF5722"),
                    Color.parseColor("#F4511E"),
                    Color.parseColor("#E64A19"),
                    Color.parseColor("#D84315"),
                    Color.parseColor("#BF360C")
            },
            new int[]{
                    Color.parseColor("#EFEBE9"),
                    Color.parseColor("#D7CCC8"),
                    Color.parseColor("#BCAAA4"),
                    Color.parseColor("#A1887F"),
                    Color.parseColor("#8D6E63"),
                    Color.parseColor("#795548"),
                    Color.parseColor("#6D4C41"),
                    Color.parseColor("#5D4037"),
                    Color.parseColor("#4E342E"),
                    Color.parseColor("#3E2723")
            },
            new int[]{
                    Color.parseColor("#FAFAFA"),
                    Color.parseColor("#F5F5F5"),
                    Color.parseColor("#EEEEEE"),
                    Color.parseColor("#E0E0E0"),
                    Color.parseColor("#BDBDBD"),
                    Color.parseColor("#9E9E9E"),
                    Color.parseColor("#757575"),
                    Color.parseColor("#616161"),
                    Color.parseColor("#424242"),
                    Color.parseColor("#212121")
            },
            new int[]{
                    Color.parseColor("#ECEFF1"),
                    Color.parseColor("#CFD8DC"),
                    Color.parseColor("#B0BEC5"),
                    Color.parseColor("#90A4AE"),
                    Color.parseColor("#78909C"),
                    Color.parseColor("#607D8B"),
                    Color.parseColor("#546E7A"),
                    Color.parseColor("#455A64"),
                    Color.parseColor("#37474F"),
                    Color.parseColor("#263238")
            }
    };*/
    //endregion no sort

    //region sort colors (value Increment)
/*    public final int[] COLORS_TOP_SORT = new int[]{
            Color.parseColor("#009688"),
            Color.parseColor("#00BCD4"),
            Color.parseColor("#03A9F4"),
            Color.parseColor("#2196F3"),
            Color.parseColor("#3F51B5"),
            Color.parseColor("#4CAF50"),
            Color.parseColor("#607D8B"),
            Color.parseColor("#673AB7"),
            Color.parseColor("#795548"),
            Color.parseColor("#8BC34A"),
            Color.parseColor("#9C27B0"),
            Color.parseColor("#9E9E9E"),
            Color.parseColor("#CDDC39"),
            Color.parseColor("#E91E63"),
            Color.parseColor("#F44336"),
            Color.parseColor("#FF5722"),
            Color.parseColor("#FF9800"),
            Color.parseColor("#FFC107"),
            Color.parseColor("#FFEB3B")};

    public final int[][] COLORS_SUB_SORT = new int[][]{
            new int[]{
                    Color.parseColor("#004D40"),
                    Color.parseColor("#00695C"),
                    Color.parseColor("#00796B"),
                    Color.parseColor("#00897B"),
                    Color.parseColor("#009688"),
                    Color.parseColor("#00BFA5"),
                    Color.parseColor("#1DE9B6"),
                    Color.parseColor("#26A69A"),
                    Color.parseColor("#4DB6AC"),
                    Color.parseColor("#64FFDA"),
                    Color.parseColor("#80CBC4"),
                    Color.parseColor("#A7FFEB"),
                    Color.parseColor("#B2DFDB"),
                    Color.parseColor("#E0F2F1")},
            new int[]{
                    Color.parseColor("#006064"),
                    Color.parseColor("#00838F"),
                    Color.parseColor("#0097A7"),
                    Color.parseColor("#00ACC1"),
                    Color.parseColor("#00B8D4"),
                    Color.parseColor("#00BCD4"),
                    Color.parseColor("#00E5FF"),
                    Color.parseColor("#18FFFF"),
                    Color.parseColor("#26C6DA"),
                    Color.parseColor("#4DD0E1"),
                    Color.parseColor("#80DEEA"),
                    Color.parseColor("#84FFFF"),
                    Color.parseColor("#B2EBF2"),
                    Color.parseColor("#E0F7FA")},
            new int[]{
                    Color.parseColor("#0091EA"),
                    Color.parseColor("#00B0FF"),
                    Color.parseColor("#01579B"),
                    Color.parseColor("#0277BD"),
                    Color.parseColor("#0288D1"),
                    Color.parseColor("#039BE5"),
                    Color.parseColor("#03A9F4"),
                    Color.parseColor("#29B6FC"),
                    Color.parseColor("#40C4FF"),
                    Color.parseColor("#4FC3F7"),
                    Color.parseColor("#80D8FF"),
                    Color.parseColor("#81D4FA"),
                    Color.parseColor("#B3E5FC"),
                    Color.parseColor("#E1F5FE")},
            new int[]{
                    Color.parseColor("#0D47A1"),
                    Color.parseColor("#1565C0"),
                    Color.parseColor("#1976D2"),
                    Color.parseColor("#1E88E5"),
                    Color.parseColor("#2196F3"),
                    Color.parseColor("#2962FF"),
                    Color.parseColor("#2979FF"),
                    Color.parseColor("#42A5F5"),
                    Color.parseColor("#448AFF"),
                    Color.parseColor("#64B5F6"),
                    Color.parseColor("#82B1FF"),
                    Color.parseColor("#90CAF9"),
                    Color.parseColor("#BBDEFB"),
                    Color.parseColor("#E3F2FD")},
            new int[]{
                    Color.parseColor("#1A237E"),
                    Color.parseColor("#283593"),
                    Color.parseColor("#303F9F"),
                    Color.parseColor("#304FFE"),
                    Color.parseColor("#3949AB"),
                    Color.parseColor("#3D5AFE"),
                    Color.parseColor("#3F51B5"),
                    Color.parseColor("#536DFE"),
                    Color.parseColor("#5C6BC0"),
                    Color.parseColor("#7986CB"),
                    Color.parseColor("#8C9EFF"),
                    Color.parseColor("#9FA8DA"),
                    Color.parseColor("#C5CAE9"),
                    Color.parseColor("#E8EAF6")},
            new int[]{
                    Color.parseColor("#00C853"),
                    Color.parseColor("#00E676"),
                    Color.parseColor("#1B5E20"),
                    Color.parseColor("#2E7D32"),
                    Color.parseColor("#388E3C"),
                    Color.parseColor("#43A047"),
                    Color.parseColor("#4CAF50"),
                    Color.parseColor("#66BB6A"),
                    Color.parseColor("#69F0AE"),
                    Color.parseColor("#81C784"),
                    Color.parseColor("#A5D6A7"),
                    Color.parseColor("#B9F6CA"),
                    Color.parseColor("#C8E6C9"),
                    Color.parseColor("#E8F5E9")},
            new int[]{
                    Color.parseColor("#263238"),
                    Color.parseColor("#37474F"),
                    Color.parseColor("#455A64"),
                    Color.parseColor("#546E7A"),
                    Color.parseColor("#607D8B"),
                    Color.parseColor("#78909C"),
                    Color.parseColor("#90A4AE"),
                    Color.parseColor("#B0BBC5"),
                    Color.parseColor("#CFD8DC"),
                    Color.parseColor("#ECEFF1")},
            new int[]{
                    Color.parseColor("#311B92"),
                    Color.parseColor("#4527A0"),
                    Color.parseColor("#512DA8"),
                    Color.parseColor("#5E35B1"),
                    Color.parseColor("#6200EA"),
                    Color.parseColor("#651FFF"),
                    Color.parseColor("#673AB7"),
                    Color.parseColor("#7C4DFF"),
                    Color.parseColor("#7E57C2"),
                    Color.parseColor("#9575CD"),
                    Color.parseColor("#B388FF"),
                    Color.parseColor("#B39DDB"),
                    Color.parseColor("#D1C4E9"),
                    Color.parseColor("#EDE7F6")},
            new int[]{
                    Color.parseColor("#3E2723"),
                    Color.parseColor("#4E342E"),
                    Color.parseColor("#5D4037"),
                    Color.parseColor("#6D4C41"),
                    Color.parseColor("#795548"),
                    Color.parseColor("#8D6E63"),
                    Color.parseColor("#A1887F"),
                    Color.parseColor("#BCAAA4"),
                    Color.parseColor("#D7CCC8"),
                    Color.parseColor("#EFEBE9")},
            new int[]{
                    Color.parseColor("#33691E"),
                    Color.parseColor("#558B2F"),
                    Color.parseColor("#64DD17"),
                    Color.parseColor("#689F38"),
                    Color.parseColor("#76FF03"),
                    Color.parseColor("#7CB342"),
                    Color.parseColor("#8BC34A"),
                    Color.parseColor("#9CCC65"),
                    Color.parseColor("#AED581"),
                    Color.parseColor("#B2FF59"),
                    Color.parseColor("#C5E1A5"),
                    Color.parseColor("#CCFF90"),
                    Color.parseColor("#DCEDC8"),
                    Color.parseColor("#F1F8E9")},
            new int[]{
                    Color.parseColor("#4A148C"),
                    Color.parseColor("#6A1B9A"),
                    Color.parseColor("#7B1FA2"),
                    Color.parseColor("#8E24AA"),
                    Color.parseColor("#9C27B0"),
                    Color.parseColor("#AA00FF"),
                    Color.parseColor("#AB47BC"),
                    Color.parseColor("#BA68C8"),
                    Color.parseColor("#CE93D8"),
                    Color.parseColor("#D500F9"),
                    Color.parseColor("#E040FB"),
                    Color.parseColor("#E1BEE7"),
                    Color.parseColor("#EA80FC"),
                    Color.parseColor("#F3E5F5")},
            new int[]{
                    Color.parseColor("#000000"),
                    Color.parseColor("#212121"),
                    Color.parseColor("#424242"),
                    Color.parseColor("#616161"),
                    Color.parseColor("#757575"),
                    Color.parseColor("#9E9E9E"),
                    Color.parseColor("#BDBDBD"),
                    Color.parseColor("#E0E0E0"),
                    Color.parseColor("#EEEEEE"),
                    Color.parseColor("#F5F5F5"),
                    Color.parseColor("#FAFAFA"),
                    Color.parseColor("#FFFFFF")},
            new int[]{
                    Color.parseColor("#827717"),
                    Color.parseColor("#9E9D24"),
                    Color.parseColor("#A4B42B"),
                    Color.parseColor("#AEEA00"),
                    Color.parseColor("#C0CA33"),
                    Color.parseColor("#C6FF00"),
                    Color.parseColor("#CDDC39"),
                    Color.parseColor("#D4E157"),
                    Color.parseColor("#DCE775"),
                    Color.parseColor("#E6EE9C"),
                    Color.parseColor("#EEFF41"),
                    Color.parseColor("#F0F4C3"),
                    Color.parseColor("#F4FF81"),
                    Color.parseColor("#F9FBE7")},
            new int[]{
                    Color.parseColor("#880E4F"),
                    Color.parseColor("#AD1457"),
                    Color.parseColor("#C2185B"),
                    Color.parseColor("#C51162"),
                    Color.parseColor("#D81B60"),
                    Color.parseColor("#E91E63"),
                    Color.parseColor("#EC407A"),
                    Color.parseColor("#F06292"),
                    Color.parseColor("#F48FB1"),
                    Color.parseColor("#F50057"),
                    Color.parseColor("#F8BBD0"),
                    Color.parseColor("#FCE4EC"),
                    Color.parseColor("#FF4081"),
                    Color.parseColor("#FF80AB")},
            new int[]{
                    Color.parseColor("#B71C1C"),
                    Color.parseColor("#C62828"),
                    Color.parseColor("#D32F2F"),
                    Color.parseColor("#D50000"),
                    Color.parseColor("#E53935"),
                    Color.parseColor("#E57373"),
                    Color.parseColor("#EF5350"),
                    Color.parseColor("#EF9A9A"),
                    Color.parseColor("#F44336"),
                    Color.parseColor("#FF1744"),
                    Color.parseColor("#FF5252"),
                    Color.parseColor("#FF8A80"),
                    Color.parseColor("#FFCDD2"),
                    Color.parseColor("#FFEBEE")},
            new int[]{
                    Color.parseColor("#BF360C"),
                    Color.parseColor("#D84315"),
                    Color.parseColor("#DD2600"),
                    Color.parseColor("#E64A19"),
                    Color.parseColor("#F4511E"),
                    Color.parseColor("#FBE9A7"),
                    Color.parseColor("#FF3D00"),
                    Color.parseColor("#FF5722"),
                    Color.parseColor("#FF6E40"),
                    Color.parseColor("#FF7043"),
                    Color.parseColor("#FF8A65"),
                    Color.parseColor("#FF9E80"),
                    Color.parseColor("#FFAB91"),
                    Color.parseColor("#FFCCBC")},
            new int[]{
                    Color.parseColor("#E65100"),
                    Color.parseColor("#EF6C00"),
                    Color.parseColor("#F57C00"),
                    Color.parseColor("#FB8C00"),
                    Color.parseColor("#FF6D00"),
                    Color.parseColor("#FF9100"),
                    Color.parseColor("#FF9800"),
                    Color.parseColor("#FFA726"),
                    Color.parseColor("#FFAB40"),
                    Color.parseColor("#FFB74D"),
                    Color.parseColor("#FFCC80"),
                    Color.parseColor("#FFD180"),
                    Color.parseColor("#FFE0B2"),
                    Color.parseColor("#FFF3E0")},
            new int[]{
                    Color.parseColor("#FF6F00"),
                    Color.parseColor("#FF8F00"),
                    Color.parseColor("#FFA000"),
                    Color.parseColor("#FFAB00"),
                    Color.parseColor("#FFB300"),
                    Color.parseColor("#FFC107"),
                    Color.parseColor("#FFC400"),
                    Color.parseColor("#FFCA28"),
                    Color.parseColor("#FFD54F"),
                    Color.parseColor("#FFD740"),
                    Color.parseColor("#FFE082"),
                    Color.parseColor("#FFE57F"),
                    Color.parseColor("#FFECB3"),
                    Color.parseColor("#FFF8E1")},
            new int[]{
                    Color.parseColor("#F57F17"),
                    Color.parseColor("#F9A825"),
                    Color.parseColor("#FBC02D"),
                    Color.parseColor("#FDD835"),
                    Color.parseColor("#FFD600"),
                    Color.parseColor("#FFEA00"),
                    Color.parseColor("#FFEB3B"),
                    Color.parseColor("#FFEE58"),
                    Color.parseColor("#FFF176"),
                    Color.parseColor("#FFF590"),
                    Color.parseColor("#FFF9C4"),
                    Color.parseColor("#FFFDE7"),
                    Color.parseColor("#FFFF00"),
                    Color.parseColor("#FFFF82")}
    };*/
    //endregion sort colors (value Increment)

    //region sort colors (value Increment)(ID)
    public final int[] COLORS_TOP_SORT = new int[]{
            R.color.lib_pick_color__md_red_500,
            R.color.lib_pick_color__md_pink_500,
            R.color.lib_pick_color__md_purple_500,
            R.color.lib_pick_color__md_deep_purple_500,
            R.color.lib_pick_color__md_indigo_500,
            R.color.lib_pick_color__md_blue_500,
            R.color.lib_pick_color__md_light_blue_500,
            R.color.lib_pick_color__md_cyan_500,
            R.color.lib_pick_color__md_teal_500,
            R.color.lib_pick_color__md_green_500,
            R.color.lib_pick_color__md_light_green_500,
            R.color.lib_pick_color__md_lime_500,
            R.color.lib_pick_color__md_yellow_500,
            R.color.lib_pick_color__md_amber_500,
            R.color.lib_pick_color__md_orange_500,
            R.color.lib_pick_color__md_deep_orange_500,
            R.color.lib_pick_color__md_brown_500,
            R.color.lib_pick_color__md_grey_500,
            R.color.lib_pick_color__md_blue_grey_500};

    public final int[][] COLORS_SUB_SORT = new int[][]{
            new int[]{
                    R.color.lib_pick_color__md_red_50,
                    R.color.lib_pick_color__md_red_100,
                    R.color.lib_pick_color__md_red_200,
                    R.color.lib_pick_color__md_red_300,
                    R.color.lib_pick_color__md_red_400,
                    R.color.lib_pick_color__md_red_500,
                    R.color.lib_pick_color__md_red_600,
                    R.color.lib_pick_color__md_red_700,
                    R.color.lib_pick_color__md_red_800,
                    R.color.lib_pick_color__md_red_900,
                    R.color.lib_pick_color__md_red_A100,
                    R.color.lib_pick_color__md_red_A200,
                    R.color.lib_pick_color__md_red_A400,
                    R.color.lib_pick_color__md_red_A700},

            new int[]{
                    R.color.lib_pick_color__md_pink_50,
                    R.color.lib_pick_color__md_pink_100,
                    R.color.lib_pick_color__md_pink_200,
                    R.color.lib_pick_color__md_pink_300,
                    R.color.lib_pick_color__md_pink_400,
                    R.color.lib_pick_color__md_pink_500,
                    R.color.lib_pick_color__md_pink_600,
                    R.color.lib_pick_color__md_pink_700,
                    R.color.lib_pick_color__md_pink_800,
                    R.color.lib_pick_color__md_pink_900,
                    R.color.lib_pick_color__md_pink_A100,
                    R.color.lib_pick_color__md_pink_A200,
                    R.color.lib_pick_color__md_pink_A400,
                    R.color.lib_pick_color__md_pink_A700},

            new int[]{
                    R.color.lib_pick_color__md_purple_50,
                    R.color.lib_pick_color__md_purple_100,
                    R.color.lib_pick_color__md_purple_200,
                    R.color.lib_pick_color__md_purple_300,
                    R.color.lib_pick_color__md_purple_400,
                    R.color.lib_pick_color__md_purple_500,
                    R.color.lib_pick_color__md_purple_600,
                    R.color.lib_pick_color__md_purple_700,
                    R.color.lib_pick_color__md_purple_800,
                    R.color.lib_pick_color__md_purple_900,
                    R.color.lib_pick_color__md_purple_A100,
                    R.color.lib_pick_color__md_purple_A200,
                    R.color.lib_pick_color__md_purple_A400,
                    R.color.lib_pick_color__md_purple_A700},

            new int[]{
                    R.color.lib_pick_color__md_deep_purple_50,
                    R.color.lib_pick_color__md_deep_purple_100,
                    R.color.lib_pick_color__md_deep_purple_200,
                    R.color.lib_pick_color__md_deep_purple_300,
                    R.color.lib_pick_color__md_deep_purple_400,
                    R.color.lib_pick_color__md_deep_purple_500,
                    R.color.lib_pick_color__md_deep_purple_600,
                    R.color.lib_pick_color__md_deep_purple_700,
                    R.color.lib_pick_color__md_deep_purple_800,
                    R.color.lib_pick_color__md_deep_purple_900,
                    R.color.lib_pick_color__md_deep_purple_A100,
                    R.color.lib_pick_color__md_deep_purple_A200,
                    R.color.lib_pick_color__md_deep_purple_A400,
                    R.color.lib_pick_color__md_deep_purple_A700},

            new int[]{
                    R.color.lib_pick_color__md_indigo_50,
                    R.color.lib_pick_color__md_indigo_100,
                    R.color.lib_pick_color__md_indigo_200,
                    R.color.lib_pick_color__md_indigo_300,
                    R.color.lib_pick_color__md_indigo_400,
                    R.color.lib_pick_color__md_indigo_500,
                    R.color.lib_pick_color__md_indigo_600,
                    R.color.lib_pick_color__md_indigo_700,
                    R.color.lib_pick_color__md_indigo_800,
                    R.color.lib_pick_color__md_indigo_900,
                    R.color.lib_pick_color__md_indigo_A100,
                    R.color.lib_pick_color__md_indigo_A200,
                    R.color.lib_pick_color__md_indigo_A400,
                    R.color.lib_pick_color__md_indigo_A700},

            new int[]{
                    R.color.lib_pick_color__md_blue_50,
                    R.color.lib_pick_color__md_blue_100,
                    R.color.lib_pick_color__md_blue_200,
                    R.color.lib_pick_color__md_blue_300,
                    R.color.lib_pick_color__md_blue_400,
                    R.color.lib_pick_color__md_blue_500,
                    R.color.lib_pick_color__md_blue_600,
                    R.color.lib_pick_color__md_blue_700,
                    R.color.lib_pick_color__md_blue_800,
                    R.color.lib_pick_color__md_blue_900,
                    R.color.lib_pick_color__md_blue_A100,
                    R.color.lib_pick_color__md_blue_A200,
                    R.color.lib_pick_color__md_blue_A400,
                    R.color.lib_pick_color__md_blue_A700},

            new int[]{
                    R.color.lib_pick_color__md_light_blue_50,
                    R.color.lib_pick_color__md_light_blue_100,
                    R.color.lib_pick_color__md_light_blue_200,
                    R.color.lib_pick_color__md_light_blue_300,
                    R.color.lib_pick_color__md_light_blue_400,
                    R.color.lib_pick_color__md_light_blue_500,
                    R.color.lib_pick_color__md_light_blue_600,
                    R.color.lib_pick_color__md_light_blue_700,
                    R.color.lib_pick_color__md_light_blue_800,
                    R.color.lib_pick_color__md_light_blue_900,
                    R.color.lib_pick_color__md_light_blue_A100,
                    R.color.lib_pick_color__md_light_blue_A200,
                    R.color.lib_pick_color__md_light_blue_A400,
                    R.color.lib_pick_color__md_light_blue_A700},

            new int[]{
                    R.color.lib_pick_color__md_cyan_50,
                    R.color.lib_pick_color__md_cyan_100,
                    R.color.lib_pick_color__md_cyan_200,
                    R.color.lib_pick_color__md_cyan_300,
                    R.color.lib_pick_color__md_cyan_400,
                    R.color.lib_pick_color__md_cyan_500,
                    R.color.lib_pick_color__md_cyan_600,
                    R.color.lib_pick_color__md_cyan_700,
                    R.color.lib_pick_color__md_cyan_800,
                    R.color.lib_pick_color__md_cyan_900,
                    R.color.lib_pick_color__md_cyan_A100,
                    R.color.lib_pick_color__md_cyan_A200,
                    R.color.lib_pick_color__md_cyan_A400,
                    R.color.lib_pick_color__md_cyan_A700},

            new int[]{
                    R.color.lib_pick_color__md_teal_50,
                    R.color.lib_pick_color__md_teal_100,
                    R.color.lib_pick_color__md_teal_200,
                    R.color.lib_pick_color__md_teal_300,
                    R.color.lib_pick_color__md_teal_400,
                    R.color.lib_pick_color__md_teal_500,
                    R.color.lib_pick_color__md_teal_600,
                    R.color.lib_pick_color__md_teal_700,
                    R.color.lib_pick_color__md_teal_800,
                    R.color.lib_pick_color__md_teal_900,
                    R.color.lib_pick_color__md_teal_A100,
                    R.color.lib_pick_color__md_teal_A200,
                    R.color.lib_pick_color__md_teal_A400,
                    R.color.lib_pick_color__md_teal_A700},

            new int[]{
                    R.color.lib_pick_color__md_green_50,
                    R.color.lib_pick_color__md_green_100,
                    R.color.lib_pick_color__md_green_200,
                    R.color.lib_pick_color__md_green_300,
                    R.color.lib_pick_color__md_green_400,
                    R.color.lib_pick_color__md_green_500,
                    R.color.lib_pick_color__md_green_600,
                    R.color.lib_pick_color__md_green_700,
                    R.color.lib_pick_color__md_green_800,
                    R.color.lib_pick_color__md_green_900,
                    R.color.lib_pick_color__md_green_A100,
                    R.color.lib_pick_color__md_green_A200,
                    R.color.lib_pick_color__md_green_A400,
                    R.color.lib_pick_color__md_green_A700},

            new int[]{
                    R.color.lib_pick_color__md_light_green_50,
                    R.color.lib_pick_color__md_light_green_100,
                    R.color.lib_pick_color__md_light_green_200,
                    R.color.lib_pick_color__md_light_green_300,
                    R.color.lib_pick_color__md_light_green_400,
                    R.color.lib_pick_color__md_light_green_500,
                    R.color.lib_pick_color__md_light_green_600,
                    R.color.lib_pick_color__md_light_green_700,
                    R.color.lib_pick_color__md_light_green_800,
                    R.color.lib_pick_color__md_light_green_900,
                    R.color.lib_pick_color__md_light_green_A100,
                    R.color.lib_pick_color__md_light_green_A200,
                    R.color.lib_pick_color__md_light_green_A400,
                    R.color.lib_pick_color__md_light_green_A700},

            new int[]{
                    R.color.lib_pick_color__md_lime_50,
                    R.color.lib_pick_color__md_lime_100,
                    R.color.lib_pick_color__md_lime_200,
                    R.color.lib_pick_color__md_lime_300,
                    R.color.lib_pick_color__md_lime_400,
                    R.color.lib_pick_color__md_lime_500,
                    R.color.lib_pick_color__md_lime_600,
                    R.color.lib_pick_color__md_lime_700,
                    R.color.lib_pick_color__md_lime_800,
                    R.color.lib_pick_color__md_lime_900,
                    R.color.lib_pick_color__md_lime_A100,
                    R.color.lib_pick_color__md_lime_A200,
                    R.color.lib_pick_color__md_lime_A400,
                    R.color.lib_pick_color__md_lime_A700},

            new int[]{
                    R.color.lib_pick_color__md_yellow_50,
                    R.color.lib_pick_color__md_yellow_100,
                    R.color.lib_pick_color__md_yellow_200,
                    R.color.lib_pick_color__md_yellow_300,
                    R.color.lib_pick_color__md_yellow_400,
                    R.color.lib_pick_color__md_yellow_500,
                    R.color.lib_pick_color__md_yellow_600,
                    R.color.lib_pick_color__md_yellow_700,
                    R.color.lib_pick_color__md_yellow_800,
                    R.color.lib_pick_color__md_yellow_900,
                    R.color.lib_pick_color__md_yellow_A100,
                    R.color.lib_pick_color__md_yellow_A200,
                    R.color.lib_pick_color__md_yellow_A400,
                    R.color.lib_pick_color__md_yellow_A700},

            new int[]{
                    R.color.lib_pick_color__md_amber_50,
                    R.color.lib_pick_color__md_amber_100,
                    R.color.lib_pick_color__md_amber_200,
                    R.color.lib_pick_color__md_amber_300,
                    R.color.lib_pick_color__md_amber_400,
                    R.color.lib_pick_color__md_amber_500,
                    R.color.lib_pick_color__md_amber_600,
                    R.color.lib_pick_color__md_amber_700,
                    R.color.lib_pick_color__md_amber_800,
                    R.color.lib_pick_color__md_amber_900,
                    R.color.lib_pick_color__md_amber_A100,
                    R.color.lib_pick_color__md_amber_A200,
                    R.color.lib_pick_color__md_amber_A400,
                    R.color.lib_pick_color__md_amber_A700},

            new int[]{
                    R.color.lib_pick_color__md_orange_50,
                    R.color.lib_pick_color__md_orange_100,
                    R.color.lib_pick_color__md_orange_200,
                    R.color.lib_pick_color__md_orange_300,
                    R.color.lib_pick_color__md_orange_400,
                    R.color.lib_pick_color__md_orange_500,
                    R.color.lib_pick_color__md_orange_600,
                    R.color.lib_pick_color__md_orange_700,
                    R.color.lib_pick_color__md_orange_800,
                    R.color.lib_pick_color__md_orange_900,
                    R.color.lib_pick_color__md_orange_A100,
                    R.color.lib_pick_color__md_orange_A200,
                    R.color.lib_pick_color__md_orange_A400,
                    R.color.lib_pick_color__md_orange_A700},

            new int[]{
                    R.color.lib_pick_color__md_deep_orange_50,
                    R.color.lib_pick_color__md_deep_orange_100,
                    R.color.lib_pick_color__md_deep_orange_200,
                    R.color.lib_pick_color__md_deep_orange_300,
                    R.color.lib_pick_color__md_deep_orange_400,
                    R.color.lib_pick_color__md_deep_orange_500,
                    R.color.lib_pick_color__md_deep_orange_600,
                    R.color.lib_pick_color__md_deep_orange_700,
                    R.color.lib_pick_color__md_deep_orange_800,
                    R.color.lib_pick_color__md_deep_orange_900,
                    R.color.lib_pick_color__md_deep_orange_A100,
                    R.color.lib_pick_color__md_deep_orange_A200,
                    R.color.lib_pick_color__md_deep_orange_A400,
                    R.color.lib_pick_color__md_deep_orange_A700},

            new int[]{
                    R.color.lib_pick_color__md_brown_50,
                    R.color.lib_pick_color__md_brown_100,
                    R.color.lib_pick_color__md_brown_200,
                    R.color.lib_pick_color__md_brown_300,
                    R.color.lib_pick_color__md_brown_400,
                    R.color.lib_pick_color__md_brown_500,
                    R.color.lib_pick_color__md_brown_600,
                    R.color.lib_pick_color__md_brown_700,
                    R.color.lib_pick_color__md_brown_800,
                    R.color.lib_pick_color__md_brown_900},

            new int[]{
                    R.color.lib_pick_color__md_grey_50,
                    R.color.lib_pick_color__md_grey_100,
                    R.color.lib_pick_color__md_grey_200,
                    R.color.lib_pick_color__md_grey_300,
                    R.color.lib_pick_color__md_grey_400,
                    R.color.lib_pick_color__md_grey_500,
                    R.color.lib_pick_color__md_grey_600,
                    R.color.lib_pick_color__md_grey_700,
                    R.color.lib_pick_color__md_grey_800,
                    R.color.lib_pick_color__md_grey_900,
                    R.color.lib_pick_color__md_black_1000,
                    R.color.lib_pick_color__md_white_1000},

            new int[]{
                    R.color.lib_pick_color__md_blue_grey_50,
                    R.color.lib_pick_color__md_blue_grey_100,
                    R.color.lib_pick_color__md_blue_grey_200,
                    R.color.lib_pick_color__md_blue_grey_300,
                    R.color.lib_pick_color__md_blue_grey_400,
                    R.color.lib_pick_color__md_blue_grey_500,
                    R.color.lib_pick_color__md_blue_grey_600,
                    R.color.lib_pick_color__md_blue_grey_700,
                    R.color.lib_pick_color__md_blue_grey_800,
                    R.color.lib_pick_color__md_blue_grey_900}
    };

    //endregion sort colors (value Increment)(ID)
}

